### ISSUE TITLE
Nuke

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#110]
People don't find nuke fun, bad feedback. We should remove it from secret, until we can figure out a scaling rework, at least ;-;

**Comment by SuperSayu** [comment]
I am not going to argue that the scaling needs a rework but you seem to have a bad habit of taking one data point as a trend.  Fully half of the nukeops vanished during the round and did not ask for admin intervention; staying on top of their situation or getting a notice when they left the valid z-levels (1 or 5, the mining level) would also help, especially since this apparently happens a lot for nukeops?

Honestly, from a tension standpoint, (living) antagonists should return to the station far more frequently than normal station members; an antagonist may _want_ to go to the derelict or whatever, but their role in the round is to be present.

If the nukeops had been able to work together it would have been a more interesting round.  ...Well, I suppose that assumes something about their ability to work together, but as a general rule...

**Comment by Profakos** [comment]
Closing as this is not a code issue, but a player issue.
