### ISSUE TITLE
People lieing on the ground are bald

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#15]

**Comment by SuperSayu** [comment]
I found it.  The update to icons recently means that some of the things in the overlays list are themselves lists; therefore there is a difference between

> for(var/thing in overlays_lying)
>  overlays += thing

and

> for(var/image/overlay in overlays_lying)
>  overlays += overlay

since this change came when I was changing things for the cloaking device I didn't acknowledge the significance of it.

This will be fixed soon.
