### ISSUE TITLE
Wigtime error

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#177]
Sometimes happens during roundstart up
runtime error: pick() from empty list
proc name: New (/obj/item/clothing/head/wig/New)
  source file: misc_special.dm,170
  usr: null
  src: the wig (/obj/item/clothing/head/wig)
//rest of the call stack is the clown closet containing it

**Comment by SuperSayu** [comment]
That's because the hairstyles list has yet to be generated during map loading.

The order of operations at game creation is roughly as follows:
- Global variables (anything defined as x=new at global scope)
- Map objects
- World/New() -> All the controller initialization, list generation, etc

hair_styles_list won't be initialized until after make_datum_references_lists() is called by world/New().  I would abort random hair in New() if the list is null, and also generate random hair in initialize() which is called well after the list is created.  If the global list exists (the object is made later), do it in new.

Alternately you could sleep or spawn the random hair but that is sloppy and bad practice.

**Comment by Profakos** [comment]
@CollenN 

So, there should probably be a sanity check for that list, and/or make it only exist in vending machines to avoid this, I suppose.

**Comment by SuperSayu** [comment]
It's not actually on the map, it was being loaded by the actorsuit (the funky suits for clown and mime that allow you to simulate wearing basically anything while on a holodeck), which spawns in the theater backstage cabinets.

I am removing it from the actorsuit for now although that would be a wonderful addition to the suit.
