### ISSUE TITLE
cloning scanner building

### ISSUE THREAD

**Issue by SuperSayu** [SuperSayu/tgstation#38]
Completing a cloning scanner makes the parts pop out
reported by: Collen

**Comment by Profakos** [comment]
Looking at the machine frame code, my only guess is that the bit where it deletes the items in the machine frame, and adds them into the newly created Machine. I think instead of setting their location as the new machine, their location becomes the machine's location instead, i.e. they are moved on top of it, instead of inside it.
Just a guess, need to be tested with the other machines too.

**Comment by SuperSayu** [comment]
No, its because when you open a scanning machine, it dumps the contents.  This was added a while ago because items were getting stuck in it with no way to retrieve them.

**Comment by Profakos** [comment]
Oh. Well, that is silly. (And I appaently misread the code, alas ;-;)

**Comment by SuperSayu** [comment]
Fixed upstream
