### ISSUE TITLE
Traitorchan

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#81]
Traitorchan needs to work again based on regular scaling, as large groups of lings it produces are not interesting anymore. Also the mode is independent of the scaling config files right now, so changing the scaling files would not prevent from that last debacle happen again.

**Comment by CollenN** [comment]
yeah

**Comment by SuperSayu** [comment]
It IS working on regular scaling, I am not using custom scaling code anymore.  And you need to make your issues more informative, I am not sure what "the mode is independent of the config files" or "that last debacle" are supposed to mean.

Give specific recommendations, not "Do whatever they're doing."  If you haven't thought it through well enough to explain correct or intended behavior, tell me exactly what the problem is and I'll deal with it.  "I trust regular scaling, not your scaling" is utterly uninformative.

Don't write issue reports knowing that we can talk about it in chat, write them to be complete in and of themselves, as though that is all I will hear on the matter.  I have a bad habit of writing issue reports as notes to myself, and will not defend that.

**Comment by Profakos** [comment]
Sorry, I meant this line "var/num_changelings = min(3,rand(1,traitors_possible-1))" should be changed to "var/num_changelings = 1", tweaked by scaling inside there.
I didn't see calls to the changeling/make_antag_chance in our code, so if it is called inside the parentmode of traitorchan, I apologize.

I apologize regardless, I won't make incomplete notes again.
